name: fraudxai
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ipykernel>=6.28
  - numpy<2.0
  - pandas>=2.0
  - scikit-learn>=1.3
  - scipy>=1.9
  - matplotlib>=3.7
  - shap>=0.44
  - xgboost>=2.0
  - lightgbm>=4.0
  - pyyaml
  - joblib
  - jupyterlab
  - notebook
  - pip
  - pip:
      - quantus>=0.6
      - lime>=0.2.0
